export interface BookMeta {
  name: string
  code: string
  testament: 'OT' | 'NT'
  chapters: number
}

export const BOOKS: BookMeta[] = [
  { name: 'Genesis',         code: 'GEN', testament: 'OT', chapters: 50 },
  { name: 'Exodus',          code: 'EXO', testament: 'OT', chapters: 40 },
  { name: 'Leviticus',       code: 'LEV', testament: 'OT', chapters: 27 },
  { name: 'Numbers',         code: 'NUM', testament: 'OT', chapters: 36 },
  { name: 'Deuteronomy',     code: 'DEU', testament: 'OT', chapters: 34 },
  { name: 'Joshua',          code: 'JOS', testament: 'OT', chapters: 24 },
  { name: 'Judges',          code: 'JDG', testament: 'OT', chapters: 21 },
  { name: 'Ruth',            code: 'RUT', testament: 'OT', chapters: 4  },
  { name: '1 Samuel',        code: '1SA', testament: 'OT', chapters: 31 },
  { name: '2 Samuel',        code: '2SA', testament: 'OT', chapters: 24 },
  { name: '1 Kings',         code: '1KI', testament: 'OT', chapters: 22 },
  { name: '2 Kings',         code: '2KI', testament: 'OT', chapters: 25 },
  { name: '1 Chronicles',    code: '1CH', testament: 'OT', chapters: 29 },
  { name: '2 Chronicles',    code: '2CH', testament: 'OT', chapters: 36 },
  { name: 'Ezra',            code: 'EZR', testament: 'OT', chapters: 10 },
  { name: 'Nehemiah',        code: 'NEH', testament: 'OT', chapters: 13 },
  { name: 'Tobit',           code: 'TOB', testament: 'OT', chapters: 14 },
  { name: 'Judith',          code: 'JDT', testament: 'OT', chapters: 16 },
  { name: 'Esther',          code: 'EST', testament: 'OT', chapters: 16 },
  { name: '1 Maccabees',     code: '1MA', testament: 'OT', chapters: 16 },
  { name: '2 Maccabees',     code: '2MA', testament: 'OT', chapters: 15 },
  { name: 'Job',             code: 'JOB', testament: 'OT', chapters: 42 },
  { name: 'Psalms',          code: 'PSA', testament: 'OT', chapters: 150 },
  { name: 'Proverbs',        code: 'PRO', testament: 'OT', chapters: 31 },
  { name: 'Ecclesiastes',    code: 'ECC', testament: 'OT', chapters: 12 },
  { name: 'Song of Songs',   code: 'SNG', testament: 'OT', chapters: 8  },
  { name: 'Wisdom',          code: 'WIS', testament: 'OT', chapters: 19 },
  { name: 'Sirach',          code: 'SIR', testament: 'OT', chapters: 51 },
  { name: 'Isaiah',          code: 'ISA', testament: 'OT', chapters: 66 },
  { name: 'Jeremiah',        code: 'JER', testament: 'OT', chapters: 52 },
  { name: 'Lamentations',    code: 'LAM', testament: 'OT', chapters: 5  },
  { name: 'Baruch',          code: 'BAR', testament: 'OT', chapters: 6  },
  { name: 'Ezekiel',         code: 'EZK', testament: 'OT', chapters: 48 },
  { name: 'Daniel',          code: 'DAN', testament: 'OT', chapters: 14 },
  { name: 'Hosea',           code: 'HOS', testament: 'OT', chapters: 14 },
  { name: 'Joel',            code: 'JOL', testament: 'OT', chapters: 4  },
  { name: 'Amos',            code: 'AMO', testament: 'OT', chapters: 9  },
  { name: 'Obadiah',         code: 'OBA', testament: 'OT', chapters: 1  },
  { name: 'Jonah',           code: 'JON', testament: 'OT', chapters: 4  },
  { name: 'Micah',           code: 'MIC', testament: 'OT', chapters: 7  },
  { name: 'Nahum',           code: 'NAH', testament: 'OT', chapters: 3  },
  { name: 'Habakkuk',        code: 'HAB', testament: 'OT', chapters: 3  },
  { name: 'Zephaniah',       code: 'ZEP', testament: 'OT', chapters: 3  },
  { name: 'Haggai',          code: 'HAG', testament: 'OT', chapters: 2  },
  { name: 'Zechariah',       code: 'ZEC', testament: 'OT', chapters: 14 },
  { name: 'Malachi',         code: 'MAL', testament: 'OT', chapters: 4  },
  { name: 'Matthew',         code: 'MAT', testament: 'NT', chapters: 28 },
  { name: 'Mark',            code: 'MRK', testament: 'NT', chapters: 16 },
  { name: 'Luke',            code: 'LUK', testament: 'NT', chapters: 24 },
  { name: 'John',            code: 'JHN', testament: 'NT', chapters: 21 },
  { name: 'Acts',            code: 'ACT', testament: 'NT', chapters: 28 },
  { name: 'Romans',          code: 'ROM', testament: 'NT', chapters: 16 },
  { name: '1 Corinthians',   code: '1CO', testament: 'NT', chapters: 16 },
  { name: '2 Corinthians',   code: '2CO', testament: 'NT', chapters: 13 },
  { name: 'Galatians',       code: 'GAL', testament: 'NT', chapters: 6  },
  { name: 'Ephesians',       code: 'EPH', testament: 'NT', chapters: 6  },
  { name: 'Philippians',     code: 'PHP', testament: 'NT', chapters: 4  },
  { name: 'Colossians',      code: 'COL', testament: 'NT', chapters: 4  },
  { name: '1 Thessalonians', code: '1TH', testament: 'NT', chapters: 5  },
  { name: '2 Thessalonians', code: '2TH', testament: 'NT', chapters: 3  },
  { name: '1 Timothy',       code: '1TI', testament: 'NT', chapters: 6  },
  { name: '2 Timothy',       code: '2TI', testament: 'NT', chapters: 4  },
  { name: 'Titus',           code: 'TIT', testament: 'NT', chapters: 3  },
  { name: 'Philemon',        code: 'PHM', testament: 'NT', chapters: 1  },
  { name: 'Hebrews',         code: 'HEB', testament: 'NT', chapters: 13 },
  { name: 'James',           code: 'JAS', testament: 'NT', chapters: 5  },
  { name: '1 Peter',         code: '1PE', testament: 'NT', chapters: 5  },
  { name: '2 Peter',         code: '2PE', testament: 'NT', chapters: 3  },
  { name: '1 John',          code: '1JN', testament: 'NT', chapters: 5  },
  { name: '2 John',          code: '2JN', testament: 'NT', chapters: 1  },
  { name: '3 John',          code: '3JN', testament: 'NT', chapters: 1  },
  { name: 'Jude',            code: 'JUD', testament: 'NT', chapters: 1  },
  { name: 'Revelation',      code: 'REV', testament: 'NT', chapters: 22 },
]

export const OT_BOOKS = BOOKS.filter(b => b.testament === 'OT')
export const NT_BOOKS = BOOKS.filter(b => b.testament === 'NT')

// Longest name first so "1 Corinthians" matches before a hypothetical shorter prefix would.
export const BOOKS_BY_NAME_LENGTH = [...BOOKS].sort((a, b) => b.name.length - a.name.length)
